workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    # Integrations fica fora de environment
    integrations:
      - app_store_connect
    environment:
      groups:
        - app_store_credentials 
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform ios
      - name: iOS Code Signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "ai.lazy.mimoo.app" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Build IPA
        script: |
          x-codebuild build-release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
