workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "Mimmo Key"
    environment:
      groups:
        - app_store_credentials 
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform ios
      - name: iOS Code Signing
        script: |
          keychain initialize
          # COMANDO CORRIGIDO:
          # 1. Sem a flag --new (que causou o erro)
          # 2. Com a flag --create (como apagamos tudo na Apple, ele vai criar um novo automático)
          # ATENÇÃO: Confirme se é "lasy" ou "lazy" abaixo!
          app-store-connect fetch-signing-files "ai.lasy.mimoo.app" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Build IPA
        script: |
          x-codebuild build-release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
